### ISSUE TITLE
What OWL serializastion should we be using for our release files?

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Turbo-Ontology#11]
- RDF/XML `.owl`, like many OBO ontologies?
- Turtle `.ttl`, which Hayden and I have found much more readable
    - and has better compatibility with some tools like TopBraid Composer

see also #8 , #9 & #10

**Comment by turbomam** [comment]
Emphasize functionality within TURBO ecosystem first. Look for places where a format is hardcoded in TURBO software.

We haven't drawn a lot of public attention to this Ontology yet anyway.

**Comment by cstoeckert** [comment]
We'll be moving to the ODK release system which generates owl files in RDF/XML. Legacy files in ttl will be kept until dependencies are updated.
