### ISSUE TITLE
Should there be a TURBO ontolgy file at the root level?

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Turbo-Ontology#9]
Currently, the TURBO native content is in `ontologies/turbo.ttl`

That has been manually merged with the OntoFox and OntoDog  OWL files as `ontologies/turbo_merged.owl`. That's the file that the automated implementation at Penn is currently downloading.

Most OBO ontology repos have a release file at the root level, like https://raw.githubusercontent.com/obi-ontology/obi/master/obi.owl

That OBI release has Ontology IRI http://purl.obolibrary.org/obo/obi.owl, which is resolved by the OBO PURL server to https://raw.githubusercontent.com/obi-ontology/obi/v2020-08-24/obi.owl, which is equivalent to the VersionIRI asserted in the https://raw.githubusercontent.com/obi-ontology/obi/master/obi.owl

We aren't using any PURL server at this point, but we should follow those patterns as much as possible.

See also #8

**Comment by turbomam** [comment]
turbo*owl at root level valuable for outreach.

Better not to maintain two release artifacts... eventually configure TURBO tools like the Semantic Engine to consume turbo*owl at root.

Check papers, especially JBI Semantic Engine paper.

Kee revision notes in GitHub repos.

**Comment by cstoeckert** [comment]
We will be generating TURBO ontology files at the root level as per the ODK make and release. The current turbo.owl is the legacy one but will be replaced with an ODK generated one for the next release.
